---
- hosts: all
  vars:
    user: iroha #your user on the remote machine

  tasks:
    - name: Download docker installation script
      get_url:
        url: https://get.docker.com
        dest: /tmp/script.sh
        mode: 0755
        validate_certs: false

    - name: Install docker using downloaded script
      shell: /tmp/script.sh
      args:
        chdir: /tmp

    - name: Add usermod to run docker from {{ user }} user
      command: usermod -aG docker {{user}}
      become: yes
    
    - name: Start docker service
      service: name=docker state=started
      become: yes
